mysql_host: 'localhost'
mysql_user: 'root'
# Enter your password in field below
mysql_password: 'Password2021'
# mysql_db: 'mysql_test'
mysql_db: 'ayj_soc_finder_prod'
# mysql_port: 3030
mysql_port: 3306